//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExamFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public int Topic_id { get; set; }
        public Nullable<int> Crs_id { get; set; }
        public string Topic_Name { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
